<!DOCTYPE html><html lang='en'><head><title>[except.special]</title><meta charset='UTF-8'/><link rel='stylesheet' type='text/css' href='14882.css'/><link rel='stylesheet' type='text/css' href='expanded.css' title='Notes and examples expanded'/><link rel='alternate stylesheet' type='text/css' href='colored.css' title='Notes and examples colored'/><link rel='icon' href='icon.png'/></head><body><div class='wrapper'><h1 ><a class='secnum' style='min-width:73pt'>14</a> Exception handling <a class='abbr_ref' href='./#except'>[except]</a></h1><h2 ><a class='secnum' style='min-width:88pt'>14.6</a> Special functions <a class='abbr_ref'>[except.special]</a></h2><div class='para' id='1'><div class='marginalizedparent'><a class='marginalized' href='#1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/exceptions.tex#L979'>#</a></div><div id='1.sentence-1' class='sentence'>The function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span> (<a href='#except.terminate'>[except.terminate]</a>)
is used by the exception
handling mechanism for coping with errors related to the exception handling
mechanism itself<a class='hidden_link' href='#1.sentence-1'>.</a></div> <div id='1.sentence-2' class='sentence'>The function
<a href='propagation'><span class='texttt'>std&#x200b;::&#x200b;current_&shy;exception()</span></a> and the class
<a href='except.nested'><span class='texttt'>std&#x200b;::&#x200b;nested_&shy;exception</span></a> can be used by a program to
capture the currently handled exception<a class='hidden_link' href='#1.sentence-2'>.</a></div></div><div id='except.terminate' class='section'><h3 ><a class='secnum' href='#except.terminate' style='min-width:103pt'>14.6.1</a> The <span class='texttt'>std&#x200b;::&#x200b;terminate</span> function <a class='abbr_ref' href='except.terminate'>[except.terminate]</a></h3><div class='para' id='except.terminate-1'><div class='marginalizedparent'><a class='marginalized' href='#except.terminate-1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/exceptions.tex#L990'>#</a></div><div id='except.terminate-1.sentence-1' class='sentence'><span class='indexparent'><a class='index' id=':terminate'></a></span>In some situations exception handling must be abandoned
for less subtle error handling techniques<a class='hidden_link' href='#except.terminate-1.sentence-1'>.</a></div> <div id='except.terminate-1.note-1' class='note'>[&nbsp;<a class='note_link' href='#except.terminate-1.note-1'><span class='textit'>Note</span></a><div class='noteBody'><span class='textit'>:</span> <div id='except.terminate-1.sentence-2' class='sentence'>These situations are:
<span class='indexparent'><a class='index' id=':terminate,called'></a></span><ul class='itemize'><li id='except.terminate-1.1'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.1'>(1.1)</a></div>when the exception handling mechanism, after completing
the initialization of the exception object
but before
activation of a handler for the exception (<a href='except.throw'>[except.throw]</a>),
calls a function that exits
via an exception, or</li><li id='except.terminate-1.2'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.2'>(1.2)</a></div>when the exception handling mechanism cannot find a handler for a thrown exception (<a href='except.handle'>[except.handle]</a>), or</li><li id='except.terminate-1.3'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.3'>(1.3)</a></div>when the search for a <a href='except.handle'>handler</a> encounters the
outermost block of a function
with a non-throwing <a href='except.spec'>exception specification</a>, or</li><li id='except.terminate-1.4'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.4'>(1.4)</a></div>when the destruction of an object during <a href='except.ctor#def:stack_unwinding'>stack unwinding</a>
terminates by throwing an exception, or</li><li id='except.terminate-1.5'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.5'>(1.5)</a></div>when initialization of a non-local
variable with static or thread storage duration (<a href='basic.start.dynamic'>[basic.start.dynamic]</a>)
exits via an exception, or</li><li id='except.terminate-1.6'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.6'>(1.6)</a></div>when destruction of an object with static or thread storage duration exits
via an exception (<a href='basic.start.term'>[basic.start.term]</a>), or</li><li id='except.terminate-1.7'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.7'>(1.7)</a></div>when execution of a function registered with
<span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>atexit</span> or <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>at_&shy;quick_&shy;exit</span>
exits via an exception (<a href='support.start.term'>[support.start.term]</a>), or</li><li id='except.terminate-1.8'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.8'>(1.8)</a></div>when a
<a class='grammarterm' href='expr.throw#nt:throw-expression'>throw-expression</a>
with no operand attempts to rethrow an exception and no exception is being
handled (<a href='except.throw'>[except.throw]</a>), or</li><li id='except.terminate-1.9'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.9'>(1.9)</a></div>when the function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>nested_&shy;exception<span class='operator'>&#x200b;::&#x200b;</span>rethrow_&shy;nested</span> is called for an object
that has captured no exception (<a href='except.nested'>[except.nested]</a>), or</li><li id='except.terminate-1.10'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.10'>(1.10)</a></div>when execution of the initial function of a thread exits via
an exception (<a href='thread.thread.constr'>[thread.thread.constr]</a>), or</li><li id='except.terminate-1.11'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.11'>(1.11)</a></div>for a parallel algorithm whose <span class='texttt'>ExecutionPolicy</span> specifies such
behavior (<a href='execpol.seq'>[execpol.seq]</a>, <a href='execpol.par'>[execpol.par]</a>, <a href='execpol.parunseq'>[execpol.parunseq]</a>),
when execution of an element access function (<a href='algorithms.parallel.defns'>[algorithms.parallel.defns]</a>)
of the parallel algorithm exits via an exception (<a href='algorithms.parallel.exceptions'>[algorithms.parallel.exceptions]</a>), or</li><li id='except.terminate-1.12'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.12'>(1.12)</a></div>when the destructor or the move assignment operator is invoked on an object
of type <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>thread</span> that refers to a joinable thread
(<a href='thread.thread.destr'>[thread.thread.destr]</a>, <a href='thread.thread.assign'>[thread.thread.assign]</a>), or</li><li id='except.terminate-1.13'><div class='marginalizedparent' style='left:-7em'><a class='marginalized' href='#except.terminate-1.13'>(1.13)</a></div>when a call to a <span class='texttt'>wait<span class='parenthesis'>(</span><span class='parenthesis'>)</span></span>, <span class='texttt'>wait_&shy;until<span class='parenthesis'>(</span><span class='parenthesis'>)</span></span>, or <span class='texttt'>wait_&shy;for<span class='parenthesis'>(</span><span class='parenthesis'>)</span></span>
function on a condition variable (<a href='thread.condition.condvar'>[thread.condition.condvar]</a>, <a href='thread.condition.condvarany'>[thread.condition.condvarany]</a>)
fails to meet a postcondition<a class='hidden_link' href='#except.terminate-1.sentence-2'>.</a></li></ul></div> â€”&nbsp;<i>end note</i></div>&nbsp;]</div> </div><div class='para' id='except.terminate-2'><div class='marginalizedparent'><a class='marginalized' href='#except.terminate-2'>2</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/exceptions.tex#L1065'>#</a></div><div id='except.terminate-2.sentence-1' class='sentence'><span class='indexparent'><a class='index' id=':terminate_'></a></span>In such cases,
the function <a href='exception.terminate'><span class='texttt'>std&#x200b;::&#x200b;terminate</span></a>
is called<a class='hidden_link' href='#except.terminate-2.sentence-1'>.</a></div> <div id='except.terminate-2.sentence-2' class='sentence'>In the situation where no matching handler is found, it is
<span class='indexparent'><a class='index' id=':stack_unwinding_before_call_to_std::terminate'></a></span>implementation-defined whether or not the
stack is unwound
before
<span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span>
is called<a class='hidden_link' href='#except.terminate-2.sentence-2'>.</a></div> <div id='except.terminate-2.sentence-3' class='sentence'>In the situation where the search for a <a href='except.handle'>handler</a> encounters the
outermost block of a function
with a non-throwing <a href='except.spec'>exception specification</a>, it is
<span class='indexparent'><a class='index' id=':whether_stack_is_unwound_before_calling_the_function_std::terminate_when_a_noexcept_specification_is_violated'></a></span>implementation-defined
whether the stack is unwound, unwound partially, or not unwound at all
before the function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span> is called<a class='hidden_link' href='#except.terminate-2.sentence-3'>.</a></div> <div id='except.terminate-2.sentence-4' class='sentence'>In all other situations, the stack shall not be unwound before
the function <span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span>
is called<a class='hidden_link' href='#except.terminate-2.sentence-4'>.</a></div> <div id='except.terminate-2.sentence-5' class='sentence'>An implementation is not permitted to finish stack unwinding
prematurely based on a determination that the unwind process
will eventually cause a call to the function
<span class='texttt'>std<span class='operator'>&#x200b;::&#x200b;</span>terminate</span><a class='hidden_link' href='#except.terminate-2.sentence-5'>.</a></div></div></div><div id='except.uncaught' class='section'><h3 ><a class='secnum' href='#except.uncaught' style='min-width:103pt'>14.6.2</a> The <span class='texttt'>std&#x200b;::&#x200b;uncaught_&shy;exceptions()</span> function <a class='abbr_ref' href='except.uncaught'>[except.uncaught]</a></h3><span class='indexparent'><a class='index' id='lib:uncaught_exceptions'></a></span><div class='para' id='except.uncaught-1'><div class='marginalizedparent'><a class='marginalized' href='#except.uncaught-1'>1</a></div><div class='sourceLinkParent'><a class='sourceLink' href='https://github.com/cplusplus/draft/tree/3a3350ee86fb2dbc86752af66d56102d237d8c4f/source/exceptions.tex#L1095'>#</a></div><div id='except.uncaught-1.sentence-1' class='sentence'>An exception is considered uncaught
after completing the initialization of the <a href='except.throw#def:exception_handling,exception_object'>exception object</a>
until completing the activation of a handler for the exception (<a href='except.handle'>[except.handle]</a>)<a class='hidden_link' href='#except.uncaught-1.sentence-1'>.</a></div> <div id='except.uncaught-1.note-1' class='note'>[&nbsp;<a class='note_link' href='#except.uncaught-1.note-1'><span class='textit'>Note</span></a><div class='noteBody'><span class='textit'>:</span> <div id='except.uncaught-1.sentence-2' class='sentence'>As a consequence, an exception is considered uncaught
during any stack unwinding resulting from it being thrown<a class='hidden_link' href='#except.uncaught-1.sentence-2'>.</a></div> â€”&nbsp;<i>end note</i></div>&nbsp;]</div>  <div id='except.uncaught-1.sentence-3' class='sentence'>
If an exception is rethrown (<a href='expr.throw'>[expr.throw]</a>, <a href='propagation'>[propagation]</a>),
it is considered uncaught from the point of rethrow
until the rethrown exception is caught<a class='hidden_link' href='#except.uncaught-1.sentence-3'>.</a></div> <div id='except.uncaught-1.sentence-4' class='sentence'>The function <a href='uncaught.exceptions'><span class='texttt'>std&#x200b;::&#x200b;uncaught_&shy;exceptions()</span></a>
returns the number of uncaught exceptions in the current thread<a class='hidden_link' href='#except.uncaught-1.sentence-4'>.</a></div> </div></div></div></body></html>